from datetime import datetime
from app.models import db, Library, Playlist
from .playlists import p1, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21, p22, p23, p24, p25, p26, p27

def seed_library():

  l1 = Library (artist_name="Bobby McFerrin", album_name="Simple Pleasures", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/c/c7/Simple_Pleasures_cover.jpg", song_title="Don't Worry Be Happy", song_url="https://moodify.s3.amazonaws.com/Happy/Bobby+McFerrin+-+Don't+Worry+Be+Happy+(Official+Music+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l2 = Library (artist_name="Pharrell", album_name="", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/2/23/Pharrell_Williams_-_Happy.jpg", song_title="Happy", song_url="https://moodify.s3.amazonaws.com/Happy/Pharrell+Williams+-+Happy+(Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l3 = Library (artist_name="Justin Timberlake", album_name="Trolls: Original Motion Picture Soundtrack", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/0/04/Trolls_Original_Motion_Picture_Soundtrack.png", song_title="Can't Stop the Feeling", song_url="https://moodify.s3.amazonaws.com/Happy/CAN'T+STOP+THE+FEELING!+(from+DreamWorks+Animation's+_TROLLS_)+(Official+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l4 = Library (artist_name="Katrina and the Waves", album_name="Walking on Sunshine", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/2/22/Katrina-and-the-waves-walking-on-sunshine-Cover-Art.png", song_title="Walking On Sunshine", song_url="https://moodify.s3.amazonaws.com/Happy/Katrina+%26+The+Waves+-+Walking+On+Sunshine+(Official+Music+Video)+(2).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l5 = Library (artist_name="Earth, Wind, & Fire", album_name="The Best of Earth, Wind, & Fire, Vol. 1", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/9/95/BestofEarthWind%26Fire.jpg", song_title="September", song_url="https://moodify.s3.amazonaws.com/Happy/Earth%2C+Wind+%26+Fire+-+September+(Official+HD+Video)+(1).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l6 = Library (artist_name="Cyndi Lauper", album_name="She's So Unusual", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/0/09/ShesSoUnusual1984.PNG", song_title="Girls Just Wanna Have Fun", song_url="https://moodify.s3.amazonaws.com/Happy/Cyndi+Lauper+-+Girls+Just+Want+To+Have+Fun+(Official+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l7 = Library (artist_name="Outkast", album_name="Speakerboxxx/The Love Below", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/4/47/Outkast-speakerboxx-lovebelow.jpg", song_title="Hey Ya", song_url="https://moodify.s3.amazonaws.com/Happy/Outkast+-+Hey+Ya!+(Official+HD+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l8 = Library (artist_name="Black Eyed Peas", album_name="The E.N.D.", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/8/88/The_E.N.D._cover.png", song_title="I Gotta Feeling", song_url="https://moodify.s3.amazonaws.com/Happy/The+Black+Eyed+Peas+-+I+Gotta+Feeling+(Official+Music+Video)+(1).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l9 = Library (artist_name="Smashmouth", album_name="Shrek Soundtrack", album_coverart_url="https://m.media-amazon.com/images/I/71YWMP+1MWL._SL1400_.jpg", song_title="I'm a Believer", song_url="https://moodify.s3.amazonaws.com/Happy/Smash+Mouth+-+I'm+A+Believer.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l10 = Library (artist_name="Francis Skyes", album_name="", album_coverart_url="https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8dHJlZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=700&q=60", song_title="Won't Let Go", song_url="https://moodify.s3.amazonaws.com/Gloomy/Francis+Skyes+-+Won't+Let+Go.mp3", created_at=datetime.now(), updated_at=datetime.now())

  l11 = Library (artist_name="Francis Skyes", album_name="", album_coverart_url="https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8dHJlZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=700&q=60", song_title="Here and Now", song_url="https://moodify.s3.amazonaws.com/Gloomy/Francis+Skyes+-+Here+and+Now.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l12 = Library (artist_name="Alabama Shakes", album_name="Sound & Color", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/2/2d/Alabama_Shakes_-_Sound_%26_Color_album_cover.jpg", song_title="This Feeling", song_url="https://moodify.s3.amazonaws.com/Gloomy/Alabama+Shakes+++This+Feeling.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l13 = Library (artist_name="Jeff Buckley", album_name="Grace", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/e/e4/Jeff_Buckley_grace.jpg", song_title="Hallelujah", song_url="https://moodify.s3.amazonaws.com/Gloomy/Jeff+Buckley+-+Hallelujah+(Official+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l14 = Library (artist_name="Imogen Heap", album_name="Speak for Yourself", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/d/d9/Imogen_Heap_-_Speak_For_Yourself.jpg", song_title="Hide and Seek", song_url="https://moodify.s3.amazonaws.com/Gloomy/Imogen+Heap+-+Hide+And+Seek+(Official+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l15 = Library (artist_name="Coldplay", album_name="X & Y", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/thumb/2/28/Coldplay_X%26Y.svg/1920px-Coldplay_X%26Y.svg.png", song_title="Fix You", song_url="https://moodify.s3.amazonaws.com/Gloomy/Coldplay+-+Fix+You+(Official+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l16 = Library (artist_name="Labrinth", album_name="Euphoria Soundtrack Season 1 & 2", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/a/ad/Euphoria_season_1_score.jpg", song_title="I'm Tired", song_url="https://moodify.s3.amazonaws.com/Gloomy/Labrinth+%26+Zendaya+-+I'm+Tired+(From+%E2%80%9CEuphoria%E2%80%9D+An+HBO+Original+Series+%E2%80%93+Lyric+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l17 = Library (artist_name="Sinead O'Connor", album_name="The Lion and the Cobra", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/d/d5/Sinead_Lion_Cobra_Original.jpg", song_title="Drink Before the War", song_url="https://moodify.s3.amazonaws.com/Gloomy/Drink+Before+the+War.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l18 = Library (artist_name="Labrinth", album_name="Euphoria Soundtrack Season 1 & 2", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/a/ad/Euphoria_season_1_score.jpg", song_title="Still Don't Know My Name", song_url="https://moodify.s3.amazonaws.com/Gloomy/Labrinth+-+Still+Don%E2%80%99t+Know+My+Name+(Official+Video)+_+euphoria+(Original+HBO+Score).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l19 = Library (artist_name="Alanis Morissette", album_name="Jagged Little Pill", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/4/47/Alanis_Morissette_-_Jagged_Little_Pill.jpg", song_title="You Oughta Know", song_url="https://moodify.s3.amazonaws.com/Angry/Alanis+Morissette+-+You+Oughta+Know+(Official+4K+Music+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l20 = Library (artist_name="CeeLo Green", album_name="The Lady Killer", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/0/06/The_Lady_Killer_cover.jpg", song_title="Forget You", song_url="https://moodify.s3.amazonaws.com/Angry/Cee+Lo+Green+-+Forget+You+(1).mp3", created_at=datetime.now(), updated_at=datetime.now())

  l21 = Library (artist_name="Blu Cantrell", album_name="So Blu", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/4/43/So_Blu.jpg", song_title="Hit Em Up Style", song_url="https://moodify.s3.amazonaws.com/Angry/Blu+Cantrell+-+Hit+'Em+Up+Style+(Oops!)+(Video+Version).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l22 = Library (artist_name="Nirvana", album_name="Nevermind", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/3/3c/Smells_Like_Teen_Spirit.jpg", song_title="Smells Like Teen Spirit", song_url="https://moodify.s3.amazonaws.com/Angry/Nirvana+-+Smells+Like+Teen+Spirit+(Official+Music+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l23 = Library (artist_name="Nirvana", album_name="Nevermind", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/3/3c/Smells_Like_Teen_Spirit.jpg", song_title="Come As You Are", song_url="https://moodify.s3.amazonaws.com/Angry/Nirvana+-+Come+As+You+Are+(Official+Music+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l24 = Library (artist_name="The White Stripes", album_name="Elephant", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/1/11/Elephant%2C_The_White_Stripes.png", song_title="Seven Nation Army", song_url="https://moodify.s3.amazonaws.com/Angry/The+White+Stripes+-+Seven+Nation+Army+(Official+Music+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l25 = Library (artist_name="DMX", album_name="Cradle 2 the Grave Soundtrack", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/2/20/Cradle_2_the_Grave_ST.jpg", song_title="X Gonna Give It To You", song_url="https://moodify.s3.amazonaws.com/Angry/DMX+-+X+Gon'+Give+It+To+Ya+(CLEAN)+%5BHQ%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l26 = Library (artist_name="Eminem", album_name="8 Mile Soundtrack", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/3/39/8milecover.jpg", song_title="Lose Yourself", song_url="https://moodify.s3.amazonaws.com/Angry/Eminem+-+Lose+Yourself+(Clean).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l27 = Library (artist_name="Kanye West", album_name="Graduation", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/7/70/Graduation_%28album%29.jpg", song_title="Stronger", song_url="https://moodify.s3.amazonaws.com/Angry/DMX+-+X+Gon'+Give+It+To+Ya+(CLEAN)+%5BHQ%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l28 = Library(artist_name="Sia feat.David Guetta", album_name="Music", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/e/e8/Music%2C_Songs_from_and_Inspired_by_the_Motion_Picture_by_Sia.jpeg", song_title="Floating Through Space", song_url="https://moodify.s3.amazonaws.com/Energetic/Dance+With+Me/Sia+and+David+Guetta+-+Floating+Through+Space+(Official).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l29 = Library(artist_name="Skrillex feat.Justin Bieber", album_name=" Skrillex and Diplo Present Jack U", album_coverart_url="https://i1.sndcdn.com/artworks-000113782825-od04gn-t500x500.jpg", song_title="Where Are U Now", song_url="https://moodify.s3.amazonaws.com/Energetic/Dance+With+Me/Skrillex%2C+Diplo%2C+Justin+Bieber+-+Where+Are+U+Now+(Lyrics).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l30 = Library(artist_name="Avicii", album_name="Levels", album_coverart_url="https://m.media-amazon.com/images/I/61Mlz6e728L._SL1182_.jpg", song_title="Levels", song_url="https://moodify.s3.amazonaws.com/Energetic/Summer+Festival+Vibes/Levels+(Radio+Edit).mp3", created_at=datetime.now(), updated_at=datetime.now())

  l31 = Library(artist_name="Lana Del Rey feat.Cedric Gervais", album_name="Born to Die: The Paradise Edition", album_coverart_url="https://i.scdn.co/image/ab67616d0000b273f894be72a77b1488292672c7", song_title="Summertime Sadness", song_url="https://moodify.s3.amazonaws.com/Energetic/Let's+Party/Lana+Del+Rey+vs+Cedric+Gervais+'Summertime+Sadness'+Remix.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l32 = Library(artist_name="Swedish House Mafia feat.Pharrell", album_name="Until One", album_coverart_url="https://img.yumpu.com/51837277/1/500x640/book-edition-swedish-house-mafia.jpg", song_title="One", song_url="https://moodify.s3.amazonaws.com/Energetic/Summer+Festival+Vibes/Swedish+House+Mafia+-+One+(Your+Name)+ft.+Pharrell.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l33 = Library(artist_name="Calvin Harris feat.Disciples", album_name="How Deep Is Your Love", album_coverart_url="https://upload.wikimedia.org/wikipedia/commons/7/74/Calvin_Harris_and_Disciples_-_How_Deep_Is_Your_Love.png", song_title="How Deep Is Your Love", song_url="https://moodify.s3.amazonaws.com/Energetic/Let's+Party/Calvin+Harris+%26+Disciples+-+How+Deep+Is+Your+Love+(Audio).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l34 = Library(artist_name="Robin Schulz feat Francesco Yates", album_name="Sugar", album_coverart_url="https://m.media-amazon.com/images/I/91ucuT55yZL._SX355_.jpg", song_title="Sugar", song_url="https://moodify.s3.amazonaws.com/Energetic/Summer+Festival+Vibes/Robin+Schulz+-+Sugar+(Lyrics)+feat.+Francesco+Yates.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l35 = Library(artist_name="Polo & Pan", album_name="Caravelle", album_coverart_url="https://img.discogs.com/alWBUjsAs09tce3cDwhF1l9E6KQ=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-10375811-1510140605-2933.jpeg.jpg", song_title="Nanã", song_url="https://moodify.s3.amazonaws.com/Energetic/Let's+Party/Polo+%26+Pan+-+Nana+(official+audio).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l36 = Library(artist_name="Polo & Pan", album_name="Caravelle", album_coverart_url="https://img.discogs.com/alWBUjsAs09tce3cDwhF1l9E6KQ=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-10375811-1510140605-2933.jpeg.jpg", song_title="Arc-en-ciel", song_url="https://moodify.s3.amazonaws.com/Energetic/Let's+Party/POLO+%26+PAN+-+Arc-en-Ciel+(official+audio).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l37 = Library(artist_name="Polo & Pan", album_name="Caravelle", album_coverart_url="https://img.discogs.com/alWBUjsAs09tce3cDwhF1l9E6KQ=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-10375811-1510140605-2933.jpeg.jpg", song_title="Canopée", song_url="https://moodify.s3.amazonaws.com/Energetic/Dance+With+Me/POLO+%26+PAN+-+Canop%C3%A9e+(audio).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l38 = Library(artist_name="Sia", album_name="This Is Acting", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/f/fd/Thisisacting_albumcover.png", song_title="Cheap Thrills", song_url="https://moodify.s3.amazonaws.com/Energetic/Dance+With+Me/Sia+-+Cheap+Thrills+(Lyrics)+ft.+Sean+Paul+(1).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l39 = Library(artist_name="Naughty Boy feat.Sam Smith", album_name="Hotel Cabana", album_coverart_url="https://img.apmcdn.org/623dfa9d74dbe6e743721ff36c3b92abfba847a4/square/018c7f-20131104-naughty-boy.jpg", song_title="La la la", song_url="https://moodify.s3.amazonaws.com/Energetic/Dance+With+Me/Naughty+Boy+-+La+la+la+ft.+Sam+Smith+(Official+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l40 = Library(artist_name="Naughty Boy feat.Beyoncé, Arrow Benjamin", album_name="Runnin' (Lose It All)", album_coverart_url="https://m.media-amazon.com/images/I/81d1Eu4nYFL._SS500_.jpg", song_title="Runnin'(Lose It All)", song_url="https://moodify.s3.amazonaws.com/Energetic/Summer+Festival+Vibes/Naughty+Boy++_+Runnin'+(Lose+It+All)++ft.+Beyonc%C3%A9%2C+Arrow+Benjamin+Lyrics.mp3", created_at=datetime.now(), updated_at=datetime.now())

  l41 = Library(artist_name="Ava Max", album_name="Heaven & Hell", album_coverart_url="https://images-na.ssl-images-amazon.com/images/I/71ZJJs0MtAL._AC_UL600_SR600,600_.jpg", song_title="My Head & My Heart", song_url="https://moodify.s3.amazonaws.com/Energetic/Let's+Party/Ava+Max+-+My+Head+%26+My+Heart+%5BOfficial+Music+Video%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l42 = Library(artist_name="David Guetta feat.Bebe Rexha & J Balvin", album_name="7", album_coverart_url="https://cdns-images.dzcdn.net/images/cover/4df59dea8621bdb8b9fc1046d795adfb/500x500.jpg", song_title="Say My Name", song_url="https://moodify.s3.amazonaws.com/Energetic/Let's+Party/David+Guetta%2C+Bebe+Rexha+%26+J+Balvin+-+Say+My+Name+(Official+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l43 = Library(artist_name="Odesza", album_name="A Moment Apart", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/1/1a/A_Moment_Alone_Cover.jpg", song_title="A Moment Apart", song_url="https://moodify.s3.amazonaws.com/Energetic/Summer+Festival+Vibes/ODESZA+-+A+Moment+Apart+(1).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l44 = Library(artist_name="Odesza feat.Zyra", album_name="In Return", album_coverart_url="https://indiecurrent.com/wp-content/uploads/2014/07/ODESZA-Memories-That-You-Call-feat.-Monsoonsiren.jpg", song_title="Say My Name", song_url="https://moodify.s3.amazonaws.com/Energetic/Summer+Festival+Vibes/ODESZA+-+Say+My+Name+(feat.+Zyra)+-+Lyric+Video.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l45 = Library(artist_name="Claude Debussy", album_name="Arabesque No.1 in E Major", album_coverart_url="https://m.media-amazon.com/images/I/512tZRxLCzL.jpg", song_title="Arabesque", song_url="https://moodify.s3.amazonaws.com/Productive/Debussy+-+Arabesque+No.+1+(Ciccolini).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l46 = Library(artist_name="Ludovico Einaudi", album_name="Seven Days Walking", album_coverart_url="https://cdns-images.dzcdn.net/images/cover/48d7e8d18fb9cba3e9a84db26de52e54/264x264.jpg", song_title="Ascent", song_url="https://moodify.s3.amazonaws.com/Productive/Einaudi_+Ascent+(Day+1).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l47 = Library(artist_name="Fabrizio Paterlini", album_name="Viaggi in Aeromobile", album_coverart_url="https://i1.sndcdn.com/artworks-000001186025-1aawf9-t500x500.jpg", song_title="Sofia la Notte", song_url="https://moodify.s3.amazonaws.com/Productive/Fabrizio+Paterlini+-+Soffia+la+Notte+_+Piano.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l48 = Library(artist_name="Yiruma", album_name="First Love", album_coverart_url="https://upload.wikimedia.org/wikipedia/en/9/91/Yiruma_-_firstlove.png", song_title="River Flows In You", song_url="https://moodify.s3.amazonaws.com/Productive/Productive+Morning/River+Flows+In+You.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l49 = Library(artist_name="Phil France", album_name="The Swimmer", album_coverart_url="https://f4.bcbits.com/img/a2399852266_10.jpg", song_title="The Swimmer", song_url="https://moodify.s3.amazonaws.com/Productive/Zone-Out/Phil+France+-+The+Swimmer.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l50 = Library(artist_name="Cœur de Pirate", album_name="Child Of Light", album_coverart_url="https://images-na.ssl-images-amazon.com/images/I/51KvDHBybNL._SY445_SX342_QL70_ML2_.jpg", song_title="Pilgrims on a Long Journey", song_url="https://moodify.s3.amazonaws.com/Productive/Productive+Morning/Child+of+Light++OST+01.Pilgrims+on+a+Long+Journey.mp3", created_at=datetime.now(), updated_at=datetime.now())

  l51 = Library(artist_name="Justin Hurwitz", album_name="La La Land Soundtrack", album_coverart_url="https://m.media-amazon.com/images/I/51HcXFz4C5L.jpg", song_title="City of Stars", song_url="https://moodify.s3.amazonaws.com/Productive/Productive+Morning/La+La+Land+-+City+of+Stars+(Piano+Cover).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l52 = Library(artist_name="Alexis Ffrench", album_name="Bluebird", album_coverart_url="https://m.media-amazon.com/images/I/716GnE4vaNL._SS500_.jpg", song_title="Bluebird", song_url="https://moodify.s3.amazonaws.com/Productive/Zone-Out/Alexis+Ffrench+-+Bluebird.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l53 = Library(artist_name="Claude Debussy", album_name="Rêverie", album_coverart_url="https://m.media-amazon.com/images/I/71CQ6YqwppL._SS500_.jpg", song_title="Rêverie", song_url="https://moodify.s3.amazonaws.com/Productive/Zone-Out/Debussy+-+R%C3%AAverie.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l54 = Library(artist_name="Claude Debussy", album_name="Clair de Lune", album_coverart_url="https://m.media-amazon.com/images/I/51rds5ch2QL._SS500_.jpg", song_title="Clair de Lune", song_url="https://moodify.s3.amazonaws.com/Productive/Claire+De+Lune.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l55 = Library(artist_name="Satyr", album_name="Barefoot", album_coverart_url="https://f4.bcbits.com/img/a2702560174_10.jpg", song_title="Barefoot", song_url="https://moodify.s3.amazonaws.com/Chill/Chilled+Soul/Barefoot+%5BySdAkc_xcK8%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l56 = Library(artist_name="Lemeria", album_name="Lemeria's Chill Beats", album_coverart_url="https://f4.bcbits.com/img/a1771540026_10.jpg", song_title="Arrival", song_url="https://moodify.s3.amazonaws.com/Chill/Chilled+Soul/Lemeria+-+Arrival+%5BF2ZmLZetSfY%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l57 = Library(artist_name="Lemeria", album_name="Lemeria's Chill Beats", album_coverart_url="https://f4.bcbits.com/img/a3256841928_10.jpg", song_title="Rainy Town", song_url="https://moodify.s3.amazonaws.com/Chill/Chilled+Soul/Lemeria+-+Rainy+Town+%5B_shBlXH75K8%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l58 = Library(artist_name="Juniorodeo", album_name="Before Sunrise", album_coverart_url="https://f4.bcbits.com/img/a0515233722_10.jpg", song_title="Fig Trees", song_url="https://moodify.s3.amazonaws.com/Chill/Wake+Up+Early/Dillan+Witherow+-+Fig+Trees+Ft.+Blue+Wednesday+%5BSkvP5v2IX9I%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l59 = Library(artist_name="Juniorodeo", album_name="Before Sunrise", album_coverart_url="https://f4.bcbits.com/img/a0515233722_10.jpg", song_title="Opposite Ends", song_url="https://moodify.s3.amazonaws.com/Chill/Wake+Up+Early/Opposite+Ends+%5BlOBn2AEGatU%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l60 = Library(artist_name="Juniorodeo", album_name="Before Sunrise", album_coverart_url="https://f4.bcbits.com/img/a0515233722_10.jpg", song_title="Field of Stars", song_url="https://moodify.s3.amazonaws.com/Chill/Wake+Up+Early/Field+of+Stars+%5Bc15svKDjIpQ%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())

  l61 = Library(artist_name="Juniorodeo", album_name="Before Sunrise", album_coverart_url="https://f4.bcbits.com/img/a0515233722_10.jpg", song_title="Rose Bay", song_url="https://moodify.s3.amazonaws.com/Chill/Light+Hits/Rose+Bay+%5BW1VE33ACovg%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l62 = Library(artist_name="Middle School", album_name="Passing Notes", album_coverart_url="https://images.genius.com/b408fc0d3c48656971d4f7921e5cbd8c.1000x1000x1.jpg", song_title="By The Window", song_url="https://moodify.s3.amazonaws.com/Chill/Light+Hits/Middle+School+-+By+The+Window+%5B8fzRN5rCt80%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l63 = Library(artist_name="Middle School", album_name="Passing Notes", album_coverart_url="https://images.genius.com/b408fc0d3c48656971d4f7921e5cbd8c.1000x1000x1.jpg", song_title="Chit Chat", song_url="https://moodify.s3.amazonaws.com/Chill/Light+Hits/Chit+Chat+%5Ba8duAFOROYM%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l64 = Library(artist_name="Ever So Blue", album_name="Calme", album_coverart_url="https://i1.sndcdn.com/artworks-jzTtSk5lSBSe-0-t500x500.png", song_title="Calme", song_url="https://moodify.s3.amazonaws.com/Serene/Live+in+Harmony/Calme+%5BoeBAzkcA-Kk%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l65 = Library(artist_name="Ever So Blue", album_name="Remembering", album_coverart_url="https://i1.sndcdn.com/artworks-ObbzwvOq1DXX-0-t500x500.png", song_title="Remembering", song_url="https://moodify.s3.amazonaws.com/Serene/Live+in+Harmony/+Remembering+by+Ever+So+Blue+%5BRFv5Tit6yW4%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l66 = Library(artist_name="Akane", album_name="Color Me Blue", album_coverart_url="https://i.ytimg.com/vi/YguvZnzjrsU/maxresdefault.jpg", song_title="Color Me Blue", song_url="https://moodify.s3.amazonaws.com/Serene/Live+in+Harmony/Color+Me+Blue+%5BYguvZnzjrsU%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l67 = Library(artist_name="Mauro Cangemi", album_name="Continuo", album_coverart_url="https://acloserlisten.files.wordpress.com/2020/11/apparat.jpg?w=710&h=710", song_title="Continuo", song_url="https://moodify.s3.amazonaws.com/Serene/Cool+Off+Time/Continuo+%5Bk6aLLVX1D7Y%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l68 = Library(artist_name="Anna Goya", album_name="Reflect", album_coverart_url="https://i.ytimg.com/vi/ClFRhlwpd68/maxresdefault.jpg", song_title="Reflect", song_url="https://moodify.s3.amazonaws.com/Serene/Cool+Off+Time/reflect+%5BClFRhlwpd68%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l69 = Library(artist_name="Dexter Mills", album_name="Unfinished Story", album_coverart_url="https://m.media-amazon.com/images/I/71C-xoSS78L._SS500_.jpg", song_title="Unfinished Story", song_url="https://moodify.s3.amazonaws.com/Serene/Cool+Off+Time/Unfinished+Story+%5BRmUmLA3vp6I%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l70 = Library(artist_name="The Piano Guys", album_name="The Piano Guys 2", album_coverart_url="https://i0.wp.com/www.cuebeatz.com/wp-content/uploads/2020/11/4c58e5ee0b286f41caa23444ea103a45.jpg?fit=640%2C640&ssl=1", song_title="Just The Way You Are", song_url="https://moodify.s3.amazonaws.com/Serene/Know+your+serene/Just+the+Way+You+Are+-+Bruno+Mars+(Piano_Cello+Cover)+-+The+Piano+Guys+%5BrIBRcQdzWQs%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())

  l71 = Library(artist_name="Flying Fingers", album_name="Peaches", album_coverart_url="https://i.pinimg.com/originals/a2/36/d5/a236d5ab852d9e36351ca73f37ed9341.jpg", song_title="Peaches", song_url="https://moodify.s3.amazonaws.com/Serene/Know+your+serene/Peaches+(Piano+Version)+%5BYlexN7WqQUo%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l72 = Library(artist_name="Leyland Moore", album_name="Traces", album_coverart_url="https://images.fineartamerica.com/images-medium-large-5/abstract-art-blue-square-three-ann-powell.jpg", song_title="Traces", song_url="https://moodify.s3.amazonaws.com/Serene/Know+your+serene/Traces+%5B-qvQuI8JLgM%5D.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l73 = Library(artist_name="John Legend", album_name="Love In The Future", album_coverart_url="https://hiphop-n-more.com/wp-content/uploads/2013/07/john-legend-love-in-the-future.jpg", song_title="All of Me", song_url="https://moodify.s3.amazonaws.com/Romantic/John+Legend+-+All+of+Me.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l74 = Library(artist_name="Marvin Gaye", album_name="Let's Get It On", album_coverart_url="https://whythebeatlesarestillrelevant.files.wordpress.com/2020/05/marvin-gaye-lets-get-it-on.jpg", song_title="Let's Get It On", song_url="https://moodify.s3.amazonaws.com/Romantic/Lets+Get+It+On+++Marvin+Gaye+Lyrics+++YouTube.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l75 = Library(artist_name="Marvin Gaye", album_name="Let's Get It On", album_coverart_url="https://whythebeatlesarestillrelevant.files.wordpress.com/2020/05/marvin-gaye-lets-get-it-on.jpg", song_title="Please Stay (Once You Go Away)", song_url="https://moodify.s3.amazonaws.com/Romantic/Marvin+Gaye+_+Please+Stay+(Once+You+Go+Away).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l76 = Library(artist_name="Marvin Gaye", album_name="Let's Get It On", album_coverart_url="https://whythebeatlesarestillrelevant.files.wordpress.com/2020/05/marvin-gaye-lets-get-it-on.jpg", song_title="If I Should Die Tonight", song_url="https://moodify.s3.amazonaws.com/Romantic/Marvin+Gaye+_+If+I+Should+Die+Tonight.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l77 = Library(artist_name="Marvin Gaye", album_name="Let's Get It On", album_coverart_url="https://whythebeatlesarestillrelevant.files.wordpress.com/2020/05/marvin-gaye-lets-get-it-on.jpg", song_title="Just To Keep You Satisfied", song_url="https://moodify.s3.amazonaws.com/Romantic/Marvin+Gaye+-+Just+To+Keep+You+Satisfied.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l78 = Library(artist_name="Whitney Houston", album_name="The Bodyguard", album_coverart_url="https://cdn.smehost.net/whitneyhoustoncom-uslegacyprod/wp-content/uploads/2018/11/04_thebodyguard_v2-1024x1024.jpg", song_title="I Will Always Love You", song_url="https://moodify.s3.amazonaws.com/Romantic/Whitney+Houston+-+I+Will+Always+Love+You+-+Lyrics.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l79 = Library(artist_name="The Beach Boys", album_name="50 Big Ones: Greatest Hits", album_coverart_url="https://img.discogs.com/Ld28UcjCrlZKPPEgESFKBiT3S-Y=/fit-in/600x579/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-4661752-1371425577-8857.jpeg.jpg", song_title="God Only Knows", song_url="https://moodify.s3.amazonaws.com/Romantic/Beach+Boys+-+God+Only+Knows+lyrics+(Lyric+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l80 = Library(artist_name="Ed Sheeran", album_name="Divide", album_coverart_url="https://metrotoparis.com/wp-content/uploads/2017/12/C1Lg3RvUQAQqHmZ.jpg", song_title="Perfect", song_url="https://moodify.s3.amazonaws.com/Romantic/Perfect+-+Ed+Sheeran+(Lyrics).mp3", created_at=datetime.now(), updated_at=datetime.now())

  l81 = Library(artist_name="Thomas Rhett", album_name="Tangled Up", album_coverart_url="https://townsquare.media/site/204/files/2015/06/cover3.jpg?w=980&q=75", song_title="Die A Happy Man", song_url="https://moodify.s3.amazonaws.com/Romantic/Thomas+Rhett+-+Die+A+Happy+Man+(Lyrics+_+Lyric+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l82 = Library(artist_name="Pat Benatar", album_name="In The Heat Of The Night", album_coverart_url="https://townsquare.media/site/295/files/2014/10/Chrysalis.jpg?w=980&q=75", song_title="Heartbreaker", song_url="https://moodify.s3.amazonaws.com/Heartbreak/Pat+Benatar+-+Heartbreaker+(Lyrics).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l83 = Library(artist_name="Adele", album_name="21", album_coverart_url="https://m.media-amazon.com/images/I/71Ln3JLWyOL._SL1500_.jpg", song_title="Someone Like You", song_url="https://moodify.s3.amazonaws.com/Heartbreak/Adele+-+Someone+Like+You+(Lyrics).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l84 = Library(artist_name="Adele", album_name="21", album_coverart_url="https://m.media-amazon.com/images/I/71Ln3JLWyOL._SL1500_.jpg", song_title="Rolling In The Deep", song_url="https://moodify.s3.amazonaws.com/Heartbreak/Rolling+in+the+Deep+_+ADELE_+Lyrics.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l85 = Library(artist_name="Adele", album_name="21", album_coverart_url="https://m.media-amazon.com/images/I/71Ln3JLWyOL._SL1500_.jpg", song_title="Rumour Has It", song_url="https://moodify.s3.amazonaws.com/Heartbreak/Rumor+Has+It-+Adele+Lyrics.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l86 = Library(artist_name="Adele", album_name="21", album_coverart_url="https://m.media-amazon.com/images/I/71Ln3JLWyOL._SL1500_.jpg", song_title="Set Fire To The Rain", song_url="https://moodify.s3.amazonaws.com/Heartbreak/Adele+-+Set+Fire+To+The+Rain+LYRICS!.mp3", created_at=datetime.now(), updated_at=datetime.now())
  l87 = Library(artist_name="Taylor Swift", album_name="Red (Taylor's Version)", album_coverart_url="https://cdn.shopify.com/s/files/1/0011/4651/9637/products/GKg0cS-Y_dfc83adc-fffd-4f2f-bc1e-fbd16d6e9659_800x.png?v=1628098713", song_title="Red", song_url="https://moodify.s3.amazonaws.com/Heartbreak/Taylor+Swift+-+RED+(Lyric+Video).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l88 = Library(artist_name="Taylor Swift", album_name="Red (Taylor's Version)", album_coverart_url="https://cdn.shopify.com/s/files/1/0011/4651/9637/products/GKg0cS-Y_dfc83adc-fffd-4f2f-bc1e-fbd16d6e9659_800x.png?v=1628098713", song_title="I Knew You Were Trouble", song_url="https://moodify.s3.amazonaws.com/Heartbreak/Taylor+Swift+-+I+Knew+You+Were+Trouble+(Lyrics).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l89 = Library(artist_name="Taylor Swift", album_name="Red (Taylor's Version)", album_coverart_url="https://cdn.shopify.com/s/files/1/0011/4651/9637/products/GKg0cS-Y_dfc83adc-fffd-4f2f-bc1e-fbd16d6e9659_800x.png?v=1628098713", song_title="All Too Well", song_url="https://moodify.s3.amazonaws.com/Heartbreak/All+Too+Well+_+Taylor+Swift+(Lyrics).mp3", created_at=datetime.now(), updated_at=datetime.now())
  l90 = Library(artist_name="Taylor Swift", album_name="Red (Taylor's Version)", album_coverart_url="https://cdn.shopify.com/s/files/1/0011/4651/9637/products/GKg0cS-Y_dfc83adc-fffd-4f2f-bc1e-fbd16d6e9659_800x.png?v=1628098713", song_title="We Are Never Ever Getting Back Together", song_url="https://moodify.s3.amazonaws.com/Heartbreak/Taylor+Swift+-+We+Are+Never+Ever+Getting+Back+Together+(Lyrics).mp3", created_at=datetime.now(), updated_at=datetime.now())

  l1.playlists.append(p1)
  l2.playlists.append(p1)
  l3.playlists.append(p1)

  l4.playlists.append(p2)
  l5.playlists.append(p2)
  l6.playlists.append(p2)

  l7.playlists.append(p3)
  l8.playlists.append(p3)
  l9.playlists.append(p3)

  l10.playlists.append(p4)
  l11.playlists.append(p4)
  l12.playlists.append(p4)

  l13.playlists.append(p5)
  l14.playlists.append(p5)
  l15.playlists.append(p5)

  l16.playlists.append(p6)
  l17.playlists.append(p6)
  l18.playlists.append(p6)

  l19.playlists.append(p7)
  l20.playlists.append(p7)
  l21.playlists.append(p7)

  l22.playlists.append(p8)
  l23.playlists.append(p8)
  l24.playlists.append(p8)

  l25.playlists.append(p9)
  l26.playlists.append(p9)
  l27.playlists.append(p9)

  l39.playlists.append(p10)
  l38.playlists.append(p10)
  l37.playlists.append(p10)
  l28.playlists.append(p10)
  l33.playlists.append(p10)

  l31.playlists.append(p11)
  l41.playlists.append(p11)
  l42.playlists.append(p11)
  l29.playlists.append(p11)
  l35.playlists.append(p11)
  l36.playlists.append(p11)

  l32.playlists.append(p12)
  l30.playlists.append(p12)
  l34.playlists.append(p12)
  l44.playlists.append(p12)
  l43.playlists.append(p12)
  l40.playlists.append(p12)

  l45.playlists.append(p13)
  l46.playlists.append(p13)
  l47.playlists.append(p13)
  l54.playlists.append(p13)

  l48.playlists.append(p14)
  l50.playlists.append(p14)
  l51.playlists.append(p14)

  l52.playlists.append(p15)
  l53.playlists.append(p15)
  l49.playlists.append(p15)

  l64.playlists.append(p16)
  l65.playlists.append(p16)
  l66.playlists.append(p16)

  l67.playlists.append(p17)
  l68.playlists.append(p17)
  l69.playlists.append(p17)

  l70.playlists.append(p18)
  l71.playlists.append(p18)
  l72.playlists.append(p18)

  l61.playlists.append(p19)
  l62.playlists.append(p19)
  l63.playlists.append(p19)

  l55.playlists.append(p20)
  l56.playlists.append(p20)
  l57.playlists.append(p20)

  l58.playlists.append(p21)
  l59.playlists.append(p21)
  l60.playlists.append(p21)

  l77.playlists.append(p22)
  l80.playlists.append(p22)
  l81.playlists.append(p22)

  l76.playlists.append(p23)
  l78.playlists.append(p23)
  l79.playlists.append(p23)

  l73.playlists.append(p24)
  l74.playlists.append(p24)
  l75.playlists.append(p24)

  l82.playlists.append(p25)
  l83.playlists.append(p25)
  l87.playlists.append(p25)

  l86.playlists.append(p26)
  l88.playlists.append(p26)
  l84.playlists.append(p26)

  l85.playlists.append(p27)
  l89.playlists.append(p27)
  l90.playlists.append(p27)


  db.session.add(l1)
  db.session.add(l2)
  db.session.add(l3)
  db.session.add(l4)
  db.session.add(l5)
  db.session.add(l6)
  db.session.add(l7)
  db.session.add(l8)
  db.session.add(l9)
  db.session.add(l10)

  db.session.add(l11)
  db.session.add(l12)
  db.session.add(l13)
  db.session.add(l14)
  db.session.add(l15)
  db.session.add(l16)
  db.session.add(l17)
  db.session.add(l18)
  db.session.add(l19)
  db.session.add(l20)

  db.session.add(l21)
  db.session.add(l22)
  db.session.add(l23)
  db.session.add(l24)
  db.session.add(l25)
  db.session.add(l26)
  db.session.add(l27)
  db.session.add(l28)
  db.session.add(l29)
  db.session.add(l30)

  db.session.add(l31)
  db.session.add(l32)
  db.session.add(l33)
  db.session.add(l34)
  db.session.add(l35)
  db.session.add(l36)
  db.session.add(l37)
  db.session.add(l38)
  db.session.add(l39)
  db.session.add(l40)

  db.session.add(l41)
  db.session.add(l42)
  db.session.add(l43)
  db.session.add(l44)
  db.session.add(l45)
  db.session.add(l46)
  db.session.add(l47)
  db.session.add(l48)
  db.session.add(l49)
  db.session.add(l50)

  db.session.add(l51)
  db.session.add(l52)
  db.session.add(l53)
  db.session.add(l54)
  db.session.add(l55)
  db.session.add(l56)
  db.session.add(l57)
  db.session.add(l58)
  db.session.add(l59)
  db.session.add(l60)

  db.session.add(l61)
  db.session.add(l62)
  db.session.add(l63)
  db.session.add(l64)
  db.session.add(l65)
  db.session.add(l66)
  db.session.add(l67)
  db.session.add(l68)
  db.session.add(l69)
  db.session.add(l70)

  db.session.add(l71)
  db.session.add(l72)
  db.session.add(l73)
  db.session.add(l74)
  db.session.add(l75)
  db.session.add(l76)
  db.session.add(l77)
  db.session.add(l78)
  db.session.add(l79)
  db.session.add(l80)

  db.session.add(l81)
  db.session.add(l82)
  db.session.add(l83)
  db.session.add(l84)
  db.session.add(l85)
  db.session.add(l86)
  db.session.add(l87)
  db.session.add(l88)
  db.session.add(l89)
  db.session.add(l90)

  db.session.commit()


def undo_library():
  # this restarts everything that has been added
  db.session.execute('TRUNCATE library RESTART IDENTITY CASCADE;')
  db.session.commit()
